// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbxvnHQks3wiX9vjVK9AYnPi06LbGI3Kk',
    appId: '1:1051561767754:web:76a90a76f48bb58a4307b3',
    messagingSenderId: '1051561767754',
    projectId: 'pacerunner-backend',
    authDomain: 'pacerunner-backend.firebaseapp.com',
    storageBucket: 'pacerunner-backend.firebasestorage.app',
    measurementId: 'G-247964MX9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS_f1S8Ur6bTDr01hqbf29b6h2i1p3Kxk',
    appId: '1:1051561767754:android:cc95aebacc809b484307b3',
    messagingSenderId: '1051561767754',
    projectId: 'pacerunner-backend',
    storageBucket: 'pacerunner-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmle7gjZL5wMGladrEEjygTEytbv5H7dg',
    appId: '1:1051561767754:ios:62d6231d0315b5514307b3',
    messagingSenderId: '1051561767754',
    projectId: 'pacerunner-backend',
    storageBucket: 'pacerunner-backend.firebasestorage.app',
    iosBundleId: 'com.orzan.pacerunner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmle7gjZL5wMGladrEEjygTEytbv5H7dg',
    appId: '1:1051561767754:ios:62d6231d0315b5514307b3',
    messagingSenderId: '1051561767754',
    projectId: 'pacerunner-backend',
    storageBucket: 'pacerunner-backend.firebasestorage.app',
    iosBundleId: 'com.orzan.pacerunner',
  );
}
